<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sparrow-parent</artifactId>
        <groupId>com.sparrowzoo</groupId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath/>

    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>spring-boot-sparrow-ds-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <properties>
        <sparrow-json.version>1.0.0-SNAPSHOT</sparrow-json.version>
        <sparrow-container.version>1.0.0-SNAPSHOT</sparrow-container.version>
        <sparrow-loader.version>1.0.0-SNAPSHOT</sparrow-loader.version>
        <sparrow-starter.version>1.0.0-SNAPSHOT</sparrow-starter.version>
        <sparrow-data-source.version>1.0.0-SNAPSHOT</sparrow-data-source.version>
        <sparrow-orm.version>1.0.0-SNAPSHOT</sparrow-orm.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-json</artifactId>
            <version>${sparrow-json.version}</version>
        </dependency>

        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-container</artifactId>
            <version>${sparrow-container.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <!--bean copy-->
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-loader</artifactId>
            <version>${sparrow-loader.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-starter</artifactId>
            <version>${sparrow-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-data-source</artifactId>
            <version>${sparrow-data-source.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-orm</artifactId>
            <version>${sparrow-orm.version}</version>
        </dependency>
    </dependencies>
</project>
