<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>sparrow-parent</artifactId>
        <groupId>com.sparrowzoo</groupId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>authenticator-microservice-starter</artifactId>
    <properties>
        <sparrow-protocol.version>1.0.0-SNAPSHOT</sparrow-protocol.version>
        <sparrow.version>1.0.0-SNAPSHOT</sparrow.version>
        <authenticator-core.version>1.0.0-SNAPSHOT</authenticator-core.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow-protocol</artifactId>
            <version>${sparrow-protocol.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>sparrow</artifactId>
            <version>${sparrow.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.sparrowzoo</groupId>
            <artifactId>authenticator-core</artifactId>
            <version>${authenticator-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
